[package]
name = "proj"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytebuffer = "0.2.1"
byteorder = "1.4.3"
q_compress = "0.9.3"
tsz = "0.1.0"
zstd = "0.11.2"
